version: "3.6"

services:
  nginx:
   # image: nginx
    container_name: nginx-studyboard
    build: nginx/.
    links:
      - webapp
    restart: always
    ports:
      - "80:80"
      - "443:443"
  webapp:
    build: .
    container_name: app-studyboard
    ports:
      - "8080:8080"
