version: "3.6"

services:
  nginx:
    container_name: nginx-studyboard
    build: nginx/.
    links:
      - webapp
    restart: always
    ports:
      - "80:80"
      - "443:443"
  webapp:
    build: .
    container_name: app-studyboard
    ports:
      - "8080:8080"
  redis:
    image: redis
    container_name: redis-studyboard
    ports:
      - "6379:6379"
  zookeeper:
    image: zookeeper
    container_name: zookeeper-studyboard
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-studyboard
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "document-read:1:1"
      